version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: "@types/jest"
    versions:
    - 26.0.16
  - dependency-name: vuepress
    versions:
    - 1.5.4
  - dependency-name: "@types/fs-extra"
    versions:
    - 9.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: "@material-ui/system"
    versions:
    - 4.9.14
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: react-redux
    versions:
    - 7.1.3
