language: node_js
node_js: '10'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile --non-interactive

jobs:
  include:
    - stage: pre-test
      name: "First commit message adheres to guidelines at <a href=\"https://goo.gl/p2fr5Q\">https://goo.gl/p2fr5Q</a>"
      script:
        - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
          bash -x tools/lint-pr-commit-message.sh ${TRAVIS_PULL_REQUEST};
          fi
    - stage: test
      name: 'Lint and test'
      before_script:
        - yarn global add codecov
      script:
        - yarn run lint
        - lerna run test:coverage -- -i
      after_script:
        - codecov
