language: node_js
node_js: '10'
os:
  - linux
  - osx
cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn --frozen-lockfile --non-interactive

stages:
  - name: pre-test
    if: (type != push)
  - name: test
    if: (tag IS blank) OR (type != push) OR (repo != AimonaStudio/rrreol)
  - name: build
    if: (tag IS blank) OR (type != push) OR (repo != AimonaStudio/rrreol)
  - name: deploy
    if: (type = push) AND (repo = AimonaStudio/rrreol)

jobs:
  include:
    - stage: pre-test
      name: 'Lint commit message'
      script:
        - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
          commitlint-travis;
          fi
    - stage: test
      name: 'Lint and test'
      before_script:
        - yarn global add codecov
      script:
        - yarn run lint
        - lerna run test:coverage -- -i
      after_script:
        - codecov
    - stage: build
      name: "Build"
      script:
        - yarn run build
    - stage: deploy
      name: "Deploy"
      before_deploy:
        - yarn docs:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $ACCESS_TOKEN
        keep_history: false
        local_dir: ./docs/.vuepress/dist
        on:
          branch: master
