language: node_js
node_js: '10'

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile --non-interactive

jobs:
  include:
    - stage: pre-test
      name: 'Lint commit message'
      script:
        - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then
          commitlint-travis;
          fi
    - stage: test
      name: 'Lint and test'
      before_script:
        - yarn global add codecov
      script:
        - yarn run lint
        - lerna run test:coverage -- -i
      after_script:
        - codecov
    - stage: build
      name: "Build"
      script:
        - yarn run build
    - stage: deploy
      name: "Deploy"
      before_deploy:
        - yarn docs:build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $ACCESS_TOKEN
        keep_history: false
        local_dir: ./docs/.vuepress/dist
        on:
          branch: master
