trigger:
  branches:
    include:
      - master

jobs:
  - job: macOS_CI_Tests
    displayName: MacOS CI Tests
    pool:
      vmImage: xcode9-macos10.13
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x
    steps:
      - template: ./macos.yml
      - template: ./rrreol.yml


  - job: ubuntu_CI_Tests
    displayName: Ubuntu CI Tests
    pool:
      vmImage: ubuntu-16.04
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x

    steps:
      - template: ./linux.yml
      - template: ./rrreol.yml

  - job: windows_CI_Tests
    displayName: Windows  CI Tests
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x

    steps:
      - template: ./windows.yml
      - template: ./rrreol.yml
